# Generated by Django 5.0.2 on 2024-02-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='fix_price',
            new_name='km_price_non_perishable',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='km_price',
            new_name='km_price_perishable',
        ),
        migrations.AddField(
            model_name='pricing',
            name='base_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
