# Generated by Django 5.0.2 on 2024-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_rename_fix_price_pricing_km_price_non_perishable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
